language: c++

dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
      
script:
  - cd ../../..
  - ls
  - make -f testing_make
  - ./bin/maintest
