language: c++

dist: xenial

script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git clone https://github.com/bast/gtest-demo.git
  - cd gtest-demo
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build 
  - make tests
