language: c++

dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git clone https://github.com/bast/gtest-demo
  - cd gtest-demo
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
      
script:
  - make
  - ./bin/unit_tests
